version: '3'
services:
  prod:
    image: dbhive/main-prod
    container_name: main-prod
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
volumes:
  node_modules:
