version: '3'
services:
  test:
    image: dbhive/main-prod
    container_name: main-test
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: npm run test
volumes:
  node_modules:
