services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    ports:
      - 9187:9187
    environment: # username #password #rds-endpoint                                                       # dbname
      DATA_SOURCE_NAME: 'postgresql://n00bs:testallcaps@dbhive.cxjwyi85ug6q.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=disable'

volumes:
  grafana-storage:
